const customerData = [
  {
    custInfo: {
      Id: 148,
      Fname: "John",
      Lname: "Doe",
      ssn: "",
      DobD: 15,
      DobM: 6,
      DobY: 1990,
      Address: "123 Main St",
      AptNumber: "Apt 4",
      AptName: "Sample Apartments",
      Aptcode: "12345",
      City: "New York",
      State: "NY",
      Zip: "10001",
      HPhone1: "555",
      HPhone2: "123",
      HPhone3: "4567",
      WPhone1: "555",
      WPhone2: "987",
      WPhone3: "6543",
      DlNumber: "xxxxxxx",
      DlState: "NY",
      DlExp: "2025-12-31",
      Employer: "XYZ Corporation",
      Position: "Software Engineer",
      EmploymentYears: "5",
      PreEmployer: "ABC Inc.",
      PrePosition: "Web Developer",
      PreEmploymentYears: "2",
      MonthlyIncome: "$5000",
      YearsAtHome: "3",
      RentType: "Rent",
      MonthlyPayment: "$1500",
      MtgCmyName: "ABC Mortgage",
      HomeValue: "150000",
      ReferenceFname: "Jane",
      ReferenceLname: "Smith",
      ReferencePhone: "555-789-1234",
      ReferenceRelation: "Project Coordinator",
    },
    CoApp_CustInfo: null,
    sales: [
      {
        id: 1,
        receiptNumber: 1001,
        date: "1/15/2020",
        totalItems: 5,
        delived: 0,
        status: "Balance:$2088.24, Undelivered",
      },
      {
        id: 2,
        receiptNumber: 1002,
        date: "1/15/2021",
        totalItems: 6,
        delived: 2,
        status: "Paid Off, Undelivered",
      },
      {
        id: 3,
        receiptNumber: 1003,
        date: "1/15/2022",
        totalItems: 2,
        delived: 0,
        status: "All funds accounted for, Undelivered",
      },
    ],
  },
  {
    custInfo: {
      Id: 89,
      Fname: "jill",
      Mname: "",
      Lname: "rabbit",
      ssn: "",
      DobD: 0,
      DobM: 0,
      DobY: 0,
      Address: "1234 Test St",
      AptNumber: "",
      AptName: "",
      Aptcode: "",
      City: "Kingwood",
      State: "TEXAS",
      Zip: "77336",
      HPhone1: "456",
      HPhone2: "111",
      HPhone3: "1234",
      WPhone1: "",
      WPhone2: "",
      WPhone3: "",
      DlNumber: "",
      DlState: "",
      DlExp: "",
      Employer: "",
      Position: "",
      EmploymentYears: "",
      PreEmployer: "",
      PrePosition: "",
      PreEmploymentYears: "",
      MonthlyIncome: "",
      YearsAtHome: "",
      RentType: "",
      MonthlyPayment: "",
      MtgCmyName: "",
      HomeValue: "",
      ReferenceFname: "",
      ReferenceLname: "",
      ReferencePhone: "",
      ReferenceRelation: "",
    },
    CoApp_CustInfo: null,
    sales: [
      {
        id: 365,
        receiptNumber: 436,
        date: "6/14/2023",
        totalItems: 5,
        delived: 0,
        status: "Balance:$2088.24, Undelivered",
      },
      {
        id: 362,
        receiptNumber: 432,
        date: "5/2/2023",
        totalItems: 3,
        delived: 0,
        status: "Balance:$1137.14, Undelivered",
      },
      {
        id: 357,
        receiptNumber: 423,
        date: "5/2/2023",
        totalItems: 7,
        delived: 0,
        status: "All funds accounted for, Undelivered",
      },
    ],
  },
];

export default customerData;
